Header header

# behavior name
string name

# event type
string behavior_event_code

# event type definitions
string GOAL_ACHIEVED		= "GOAL_ACHIEVED"
string TIME_OUT			= "TIME_OUT"
string WRONG_PROGRESS		= "WRONG_PROGRESS"
string ASSUMPTION_CONFLICT	= "ASSUMPTION_CONFLICT"
string INTERRUPTED              = "INTERRUPTED"

# belief that failed
string failed_belief

# explicative message of the conflict
string belief_conflict